# Generated by Django 2.2.2 on 2019-07-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('img2', models.ImageField(upload_to='pics')),
                ('title', models.TextField(default='')),
                ('subtitle', models.TextField(default='')),
                ('sub2title', models.TextField(default='')),
                ('content_at', models.TextField(default='')),
                ('content_as', models.TextField(default='')),
                ('content_as2', models.TextField(default='')),
            ],
        ),
    ]
